[package]
name = "axum1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
axum = { version= "0.5.6", features = ["json", "headers"] }
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
serde = { version = "1.0.137", features = ["derive"] }
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "any", "postgres", "json", "macros", "chrono", "uuid", "migrate", "offline", "bigdecimal"], default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.18.0", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
log = "0.4.14"
time = { version = "0.3.9", features = ["formatting", "serde", "serde-well-known"] }
async-session = "3.0.0"
uuid = { version = "1", features = ["v4", "serde"] }
async-redis-session = "0.2.2"
tower-http = { version = "0.3.0", features = ["add-extension", "trace", "cors"] }
argon2 = { version = "0.4", features = ["std"] }
secrecy = { version = "0.8.0", features = ["serde"] } 
rand = "0.8.5"
config = "0.13.1"
axum-extra = { version = "0.3.4", features = ["cookie", "cookie-signed", "form"] }
sentry = "0.26.0"
