version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hummus
      - PGDATA=/var/lib/pg_data
    volumes:
      - ./volumes/postgres/data:/var/lib/pg_data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@dev.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    depends_on:
      - postgres

  redis:
    image: 'redis:alpine'
    command: 'redis-server'
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - './volumes/redis-data:/var/lib/redis'
